version: '3.8'

services:
  rails:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - MONGO_URL=mongodb://mongo:27017/url_shortener_development
    depends_on:
      - mongo
    volumes:
      - .:/rails
      - bundle_data:/usr/local/bundle

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

volumes:
  mongo_data:
  bundle_data:
